name: Keep Codespace Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"  # backup trigger tiap 15 menit

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Codespace KeepAlive
        run: |
          curl -sSf https://glorious-space-pancake-r4vxqxp6p69x25j4v-8080.app.github.dev/ || true

      - name: Trigger ulang workflow
        run: |
          gh workflow run "Keep Codespace Alive"
