name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # setiap 5 menit
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Codespace KeepAlive
        run: |
          curl -sSf https://glorious-space-pancake-r4vxqxp6p69x25j4v-8080.app.github.dev/ || true
